- hosts: localhost
  vars:
    source_key: './.ssh/id_ed25519'
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
    - name: WSL config
      copy:
        src: 'conf/wsl.conf'
        dest: '/etc/wsl.conf'
        mode: 0600
      become: true
      tags:
        - install
        - core
        - wsl
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/go-setup.yml
    - import_tasks: tasks/python-setup.yml
    - import_tasks: tasks/rust-setup.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/zsh-plugin-setup.yml
    - import_tasks: tasks/docker-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/lazygit-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/k9s-setup.yml
