- hosts: localhost
  tasks:
    - name: Check if curl is installed
      command: which curl
      register: curl_check
      ignore_errors: true

    - name: Install curl
      apt:
        name: curl
        state: present
      when: curl_check.rc != 0
