- name: Install biome
  get_url:
    url: https://github.com/biomejs/biome/releases/latest/download/biome-linux-x64
    dest: /tmp/biome
    mode: '0755'
  tags:
    - install
    - biome
    - linux-only

- name: Setup biome
  shell: 'install /tmp/biome /usr/local/bin'
  become: true
  tags:
    - install
    - biome
    - linux-only
