- name: Cleanup go
  shell: rm -rf /usr/local/go
  become: true
  tags:
    - install
    - golang-macos

- name: Install go
  get_url:
    url: https://go.dev/dl/go1.21.7.darwin-arm64.tar.gz
    dest: /tmp/go.darwin-arm64.tar.gz
    mode: "0755"
    force: "yes"
  tags:
    - install
    - golang-macos

- name: Setup go
  shell: tar -C /usr/local -xvf /tmp/go.darwin-arm64.tar.gz
  become: true
  tags:
    - install
    - golang-macos
