- name: Install go
  get_url:
    url: https://go.dev/dl/go1.18.10.linux-amd64.tar.gz
    dest: /tmp/go.linux-amd64.tar.gz
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - golang

- name: Setup go
  shell: tar -C /usr/local -xvf /tmp/go.linux-amd64.tar.gz
  become: true
  tags:
    - install
    - golang
