- name: Install K9S
  get_url:
    url: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
    dest: /tmp/k9s_Linux_amd64.tar.gz
    mode: '0755'
  tags:
    - install
    - k9s
    - linux-only

- name: Create a K9S Directory
  file:
    path: /usr/local/bin/k9s
    state: directory
    mode: '0755'
  become: true
  tags:
    - install
    - k9s
    - linux-only

- name: Extract K9S
  unarchive:
    src: /tmp/k9s_Linux_amd64.tar.gz
    dest: /usr/local/bin/k9s
    mode: '0755'
    remote_src: yes
  become: true
  tags:
    - install
    - k9s
    - linux-only

- name: Check if k9s PATH exists in ~/.zshrc
  command: grep -q "/usr/local/bin/k9s" ~/.zshrc
  register: is_k9s_path_set
  ignore_errors: yes
  tags:
    - install
    - k9s
    - linux-only

- name: Set K9s path
  shell: echo 'export PATH="/usr/local/bin/k9s:$PATH"' >> ~/.zshrc
  when: is_k9s_path_set.rc != 0
  tags:
    - install
    - k9s
    - linux-only
