- name: Install K9S
  get_url:
    url: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
    dest: /tmp/k9s_Linux_amd64.tar.gz
    mode: "0755"
  tags:
    - install
    - k9s
    - linux-only

- name: Setup k9s
  shell: "tar -C /tmp -xf /tmp/k9s_Linux_amd64.tar.gz && install /tmp/k9s /usr/local/bin"
  become: true
  tags:
    - install
    - k9s
    - linux-only
