- name: Download Neovim AppImage
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: /usr/local/bin/nvim.appimage
    mode: "0755"
    force: true
  become: true
  tags:
    - install
    - neovim
    - linux-only

- name: Create symbolic link for Neovim
  file:
    src: /usr/local/bin/nvim.appimage
    dest: /usr/local/bin/nvim
    state: link
    force: true
  become: true
  tags:
    - install
    - neovim
    - linux-only

- name: Download tmux AppImage
  get_url:
    url: https://github.com/kiyoon/tmux-appimage/releases/latest/download/tmux.appimage
    dest: /usr/local/bin/tmux.appimage
    mode: "0755"
    force: true
  become: true
  tags:
    - install
    - tmux
    - linux-only

- name: Create symbolic link for tmux
  file:
    src: /usr/local/bin/tmux.appimage
    dest: /usr/local/bin/tmux
    state: link
    force: true
  become: true
  tags:
    - install
    - tmux
    - linux-only

- name: Register current versions
  uri:
    url: "https://api.github.com/repos/{{ item.repo }}/releases/latest"
    return_content: yes
  register: version_responses
  loop:
    - { repo: "junegunn/fzf", name: "fzf" }
    - { repo: "jesseduffield/lazygit", name: "lazygit" }
    - { repo: "so-fancy/diff-so-fancy", name: "diff-so-fancy" }
  tags:
    - install
    - fzf
    - lazygit
    - diff-so-fancy
    - linux-only

- name: Install fzf
  unarchive:
    src: "https://github.com/junegunn/fzf/releases/latest/download/fzf-{{ (version_responses.results | selectattr('item.name', 'equalto', 'fzf') | first).json.tag_name | regex_replace('^v', '') }}-linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
    include:
      - fzf
  become: true
  tags:
    - install
    - fzf
    - linux-only

- name: Install lazygit
  unarchive:
    src: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ (version_responses.results | selectattr('item.name', 'equalto', 'lazygit') | first).json.tag_name | regex_replace('^v', '') }}_Linux_x86_64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
    include:
      - lazygit
  become: true
  tags:
    - install
    - lazygit
    - linux-only

- name: Install diff-so-fancy
  get_url:
    url: "https://github.com/so-fancy/diff-so-fancy/releases/latest/download/diff-so-fancy"
    dest: /usr/local/bin/diff-so-fancy
    mode: "0755"
    force: true
  become: true
  tags:
    - install
    - diff-so-fancy
    - lazygit
    - linux-only
