- name: Check whether mise is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise"
  register: mise_binary
  tags:
    - install
    - mise
    - linux-only

- name: Download mise installer
  ansible.builtin.get_url:
    url: https://mise.run
    dest: /tmp/install-mise.sh
    mode: "0755"
  when: not mise_binary.stat.exists
  tags:
    - install
    - mise
    - linux-only

- name: Install mise
  ansible.builtin.command: /bin/sh /tmp/install-mise.sh
  args:
    chdir: "{{ ansible_facts['env']['HOME'] }}"
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise"
  when: not mise_binary.stat.exists
  tags:
    - install
    - mise
    - linux-only
