# - name: Remove neovim
#   shell: rm -rf ~/neovim && rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim
#   tags:
#     - install
#     - neovim
#     - linux-only

- name: Download Neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /tmp/nvim.appimage
    mode: '0755'
    force: 'yes'
  tags:
    - install
    - neovim
    - linux-only

- name: Install neovim
  shell: 'rm /usr/local/bin/nvim && cp /tmp/nvim.appimage /usr/local/bin/nvim.appimage && ln -s /usr/local/bin/nvim.appimage /usr/local/bin/nvim'
  become: true
  ignore_errors: true
  tags:
    - install
    - neovim
    - linux-only
