- name: Remove neovim
  shell: rm -rf ~/neovim && rm -rf ~/.config/nvim && rm -rf ~/.local/share/nvim
  tags:
    - install
    - neovim

- name: Download Neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /tmp/nvim.appimage
    mode: "0755"
    force: "yes"
  tags:
    - install
    - neovim

- name: Install neovim
  shell: "cp /tmp/nvim.appimage /usr/local/bin/nvim.appimage && ln -s /usr/local/bin/nvim.appimage /usr/local/bin/nvim"
  become: true
  tags:
    - install
    - neovim

- name: Install nvchad
  shell: "git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1"
  tags:
    - install
    - neovim
