- name: Remove pyenv
  shell: rm -rf ~/.pyenv
  tags:
    - install
    - python

- name: Install python
  shell: curl https://pyenv.run | bash
  tags:
    - install
    - python

- name: Set up Pyenv environment variables
  shell: |
    echo 'export PYENV_ROOT="{{ lookup('env', 'HOME') }}/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  args:
    executable: /bin/bash
  tags:
    - install
    - python

- name: Reload shell profile
  shell: |
    source ~/.bashrc
  args:
    executable: /bin/bash
  tags:
    - install
    - python

- name: Install correct version of Python
  shell: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv install 3.11"
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
  tags:
    - install
    - python

- name: Use the correct version of Python
  shell: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv global 3.11"
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
  tags:
    - install
    - python
