- name: Install python
  shell: curl https://pyenv.run | bash
  tags:
    - install
    - python

- name: Install correct version of Python
  shell: pyenv install 3.11
  tags:
    - install
    - python

- name: Use the correct version of Python
  shell: pyenv global 3.11
  tags:
    - install
    - python
