background = 0xFF1D1F21
base = 0xFF282A2E
alternate_base = 0xFF343A47
text = 0xFFF5F5F5
bright_text = 0xFFFFFFFF
accent = 0xFFB4CBFF
accent_secondary = 0xFF7AA6DA
font_family = Noto Sans
font_family_monospace = GoogleSansCode Nerd Font
font_size = 11
rounding_large = 8
rounding_small = 5
