# This is for Windows alacritty configuration file.
[terminal.shell]
program = 'C:\Windows\System32\wsl.exe -d Ubuntu'
args = ["--cd ~"]

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[font]
size = 14.0

[font.normal]
family = "GeistMono Nerd Font"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
blur = true
decorations = "None"
dynamic_padding = true
dynamic_title = false
opacity = 0.99
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 10
y = 10
