# This is for Windows alacritty configuration file. (so disable the terminal.shell if on non-windows)
[general]
import = ["./tokyonight-night.toml"]

[terminal.shell]
program = 'C:\Windows\System32\wsl.exe -d Ubuntu'
args = ["--cd ~"]

[font]
size = 13.0

[font.normal]
family = "GeistMono Nerd Font"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
blur = true
decorations = "None"
# Enable for macos
# decorations = "Buttonless"
dynamic_padding = true
dynamic_title = false
opacity = 0.99
# Enable for macos (doesn't affect windows)
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 10
y = 10
