os:
  open: "code {{filename}}"
  edit: "nvim {{filename}}"
gui:
  nerdFontsVersion: "3"
  # tokyo night theme
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

  # vague color
  # authorColors:
  #   "*": "#f3be7c"
  # theme:
  #   activeBorderColor:
  #     - "#aeaed1"
  #     - "bold"
  #   inactiveBorderColor:
  #     - "#606079"
  #   optionsTextColor:
  #     - "#606079"
  #   selectedLineBgColor:
  #     - "#252530"
  #   cherryPickedCommitFgColor:
  #     - "#d8647e"
  #   cherryPickedCommitBgColor:
  #     - "bg"
  #   markedBaseCommitFgColor:
  #     - "#f3be7c"
  #   markedBaseCommitBgColor:
  #     - "bg"
  #   unstagedChangesColor:
  #     - "#d8647e"
  #   defaultFgColor:
  #     - "#cdcdcd"
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
    # pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
